"""config.py - Environment and configuration parsing for Greenbone backup.

Loads settings from environment variables, .env files, and CLI defaults.
All defaults follow the source-of-truth layout discovered from VM 202.

Copyright (C) 2026 Nethesis S.r.l.
SPDX-License-Identifier: GPL-3.0-or-later
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Optional


ENV_FILE_PATH = Path("/etc/greenbone-backup/greenbone-backup.env")

ENV_DEFAULTS: Dict[str, str] = {
    "GREENBONE_DIR": "/opt/greenbone-community",
    "COMPOSE_FILE": "/opt/greenbone-community/compose.yaml",
    "BACKUP_DIR": "/var/backups/greenbone",
    "BACKUP_BASE_DIR": "/opt/greenbone-backup",
    "TMP_DIR": "/opt/greenbone-backup/tmp",
    "LOG_FILE": "/var/log/greenbone-backup-job00.log",
    "RCLONE_REMOTE": "do:testmonbck",
    "RCLONE_PATH": "greenbone-backups/job00-daily",
    "GREENBONE_BACKUP_UPLOAD": "0",
    "RETENTION_LOCAL": "90",
    "RETENTION_CLOUD": "90",
}


@dataclass
class BackupConfig:
    """Complete configuration for a Greenbone backup operation.

    Every field has a safe default derived from VM 202 layout.
    """

    greenbone_dir: Path = Path("/opt/greenbone-community")
    compose_file: Path = Path("/opt/greenbone-community/compose.yaml")
    backup_dir: Path = Path("/var/backups/greenbone")
    backup_base_dir: Path = Path("/opt/greenbone-backup")
    tmp_dir: Path = Path("/opt/greenbone-backup/tmp")
    log_file: Path = Path("/var/log/greenbone-backup-job00.log")
    rclone_remote: str = "do:testmonbck"
    rclone_path: str = "greenbone-backups/job00-daily"
    upload_enabled: bool = False
    retention_local: int = 90
    retention_cloud: int = 90
    dry_run: bool = False

    @classmethod
    def from_env(cls, overrides: Optional[Dict[str, str]] = None) -> "BackupConfig":
        """Build a BackupConfig from env vars, .env file, and overrides.

        Priority (highest wins): overrides > environment > .env file > defaults.
        """
        raw: Dict[str, str] = dict(ENV_DEFAULTS)

        # Load from .env file if present
        if ENV_FILE_PATH.exists():
            try:
                for line in ENV_FILE_PATH.read_text(encoding="utf-8").splitlines():
                    line = line.strip()
                    if not line or line.startswith("#") or "=" not in line:
                        continue
                    key, _, val = line.partition("=")
                    raw[key.strip()] = val.strip()
            except Exception:
                pass

        # Environment overrides
        for key in ENV_DEFAULTS:
            env_val = os.environ.get(key)
            if env_val is not None:
                raw[key] = env_val

        # Explicit overrides
        if overrides:
            raw.update(overrides)

        upload_str = raw.get("GREENBONE_BACKUP_UPLOAD", "0")
        return cls(
            greenbone_dir=Path(raw["GREENBONE_DIR"]),
            compose_file=Path(raw["COMPOSE_FILE"]),
            backup_dir=Path(raw["BACKUP_DIR"]),
            backup_base_dir=Path(raw.get("BACKUP_BASE_DIR", raw["BACKUP_DIR"])),
            tmp_dir=Path(raw["TMP_DIR"]),
            log_file=Path(raw.get("LOG_FILE", "/var/log/greenbone-backup-job00.log")),
            rclone_remote=raw["RCLONE_REMOTE"],
            rclone_path=raw.get("RCLONE_PATH", "greenbone-backups/job00-daily"),
            upload_enabled=upload_str == "1",
            retention_local=int(raw.get("RETENTION_LOCAL", "90")),
            retention_cloud=int(raw.get("RETENTION_CLOUD", "90")),
        )

    def to_env_lines(self) -> str:
        """Serialize config back to .env file format.

        Only fields that match the expected env-var names are written.
        """
        lines = [
            "# Greenbone backup environment - generated by greenbone_install_backup.py",
            "# See: https://github.com/Coverup20/openvas-tools",
            "",
            "# Paths",
            f"GREENBONE_DIR={self.greenbone_dir}",
            f"COMPOSE_FILE={self.compose_file}",
            f"BACKUP_DIR={self.backup_dir}",
            f"TMP_DIR={self.tmp_dir}",
            f"LOG_FILE={self.log_file}",
            "",
            "# Cloud target (Spaces/S3 compatible)",
            f"RCLONE_REMOTE={self.rclone_remote}",
            f"RCLONE_PATH={self.rclone_path}",
            "",
            "# Upload gate (0=disabled, 1=enabled)",
            f"GREENBONE_BACKUP_UPLOAD={'1' if self.upload_enabled else '0'}",
            "",
            "# Retention",
            f"RETENTION_LOCAL={self.retention_local}",
            f"RETENTION_CLOUD={self.retention_cloud}",
            "",
        ]
        return "\n".join(lines)


# Rclone config path resolution follows Checkmk and VM 202 convention:
#   - Root: /root/.config/rclone/rclone.conf
#   - Permissions: 600 (owner read/write only)
def default_rclone_config() -> Path:
    """Return the default rclone config path (root user convention)."""
    return Path("/root/.config/rclone/rclone.conf")


def hostname_short() -> str:
    """Return short hostname for use in archive naming."""
    import socket
    return socket.gethostname().split(".")[0]
